In [12]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1, inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [14]:
target=df['Survived']
inputs=df.drop('Survived', axis='columns')

In [17]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [18]:
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [19]:
inputs.drop(['Sex'], axis='columns', inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False

In [20]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='str')

In [21]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [23]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female   male
0       3  22.000000   7.2500   False   True
1       1  38.000000  71.2833    True  False
2       3  26.000000   7.9250    True  False
3       1  35.000000  53.1000    True  False
4       3  35.000000   8.0500   False   True
5       3  29.699118   8.4583   False   True

In [24]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)
len(X_train), len(X_test)

(712, 179)

In [25]:
len(inputs)

891

In [26]:
X_train

     Pclass        Age     Fare  female  male
562       2  28.000000  13.5000   False  True
588       3  22.000000   8.0500   False  True
121       3  29.699118   8.0500   False  True
872       1  33.000000   5.0000   False  True
770       3  24.000000   9.5000   False  True
..      ...        ...      ...     ...   ...
859       3  29.699118   7.2292   False  True
169       3  28.000000  56.4958   False  True
281       3  28.000000   7.8542   False  True
688       3  18.000000   7.7958   False  True
350       3  23.000000   9.2250   False  True

[712 rows x 5 columns]

In [27]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [28]:
model.fit(X_train, y_train)

GaussianNB()

In [29]:
model.score(X_test, y_test)

0.8100558659217877

In [30]:
X_test[:10]

     Pclass        Age      Fare  female   male
659       1  58.000000  113.2750   False   True
752       3  33.000000    9.5000   False   True
727       3  29.699118    7.7375    True  False
40        3  40.000000    9.4750    True  False
601       3  29.699118    7.8958   False   True
833       3  23.000000    7.8542   False   True
490       3  29.699118   19.9667   False   True
612       3  29.699118   15.5000    True  False
493       1  71.000000   49.5042   False   True
474       3  22.000000    9.8375    True  False

In [32]:
y_test[:10]

659    0
752    0
727    1
40     0
601    0
833    0
490    0
612    1
493    0
474    0
Name: Survived, dtype: int64

In [35]:
model.predict(X_test[:10])

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1])

In [36]:
model.predict_proba(X_test[:10])

array([[0.16970627, 0.83029373],
       [0.98910974, 0.01089026],
       [0.05028047, 0.94971953],
       [0.05154672, 0.94845328],
       [0.98880223, 0.01119777],
       [0.98762807, 0.01237193],
       [0.98859883, 0.01140117],
       [0.05032624, 0.94967376],
       [0.72872132, 0.27127868],
       [0.04496931, 0.95503069]])